[tools]
neovim = "latest"
erlang = "27"
elixir = "1.17.3-otp-27"
nodejs = "22"
chezmoi = "2.55"
python = "3.12"
go = "latest"
lazygit = "latest"
delta = "latest"
java = "adoptopenjdk-17.0.6+10"
clojure = "1.12"
swift = "latest"
swiftlint = "latest"
