[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = '''
	shell 'ya emit cd "$(git rev-parse --show-toplevel)"'
'''
desc = "Goto git root directory"

[[manager.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/code"
desc = "Goto ~/code"
