# Git
abbr    gst  "git status"
abbr    gd   "git diff"
abbr    gdh  "git diff HEAD"
abbr    gc   "git clone $1 $2"
abbr    gcl  "git clean -fdx"
abbr    gcm  "git commit"
abbr    ga   "git add -u ."
abbr    gaa  "git add -A ."
abbr    gpo  "git push origin $1"
abbr    glo  "git log --color --graph --abbrev-commit --oneline"
abbr    grhh "git reset --hard HEAD"
abbr    gcp  "git cherry-pick $1"
